// Package issue579 provides primitives to interact with the openapi HTTP API.
//
// Code generated by dev.azure.com/schwarzit/schwarzit.odj.core/_git/stackit-client-generator.git version (devel) DO NOT EDIT.
package issue579

import (
	openapiTypes "dev.azure.com/schwarzit/schwarzit.odj.core/_git/stackit-client-generator.git/pkg/types"
)

// AliasedDate defines model for AliasedDate.
type AliasedDate = openapiTypes.Date

// Pet defines model for Pet.
type Pet struct {
	Born   *AliasedDate        `json:"born,omitempty"`
	BornAt *openapiTypes.Date `json:"born_at,omitempty"`
}
